services:
  # Discord bot application (uses existing n8n instance)
  discord-bot:
    build: .
    container_name: infant-discord-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - N8N_WEBHOOK=http://host.docker.internal:5678/webhook/infant-discord-webhook
      - WEBHOOK_HOST=0.0.0.0
      - WEBHOOK_PORT=8000
      - LOG_LEVEL=INFO
      - DOCKER_ENV=true
    ports:
      - "8000:8000"  # Webhook server port
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - bot-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local

networks:
  bot-network:
    driver: bridge
